# Generated by Django 4.2.11 on 2024-03-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_task_options_alter_task_deadline_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deadline_date',
            new_name='deadline',
        ),
    ]
